### ISSUE TITLE
Implement SSL/TLS API

### ISSUE THREAD

**Issue by timbobcat** [u-blox/cellular#1]
Communication with AWS IoT is only possible via secure connections, established via SSL/TLS.
This requires the use of AT+USECMNG and AT+USECPRF commands. Could you look into adding this functionality into the API, especially the part that involves importing certificates and private keys?

**Comment by RobMeades** [comment]
Hi there, apologies for the delay, not sure where notifications are going but they're not getting to me as they should.  I've just now got the thing actually working under AWS, need to try integrating it on another chipset platform and with a SARA-R5 u-blox module, will then take a look at adding security.

**Comment by timbobcat** [comment]
Hi Rob,

Thanks for the feedback! Glad to hear something is working.
If I may ask, what chipset are you considering? If you are open to suggestions, may I suggest you try using one of the Nordic chipsets, perferably the NRF52840. It's one of their most widely used chipsets.
Thanks for your time!

Tim
________________________________

**Comment by RobMeades** [comment]
Hokay, if NRF52840 is a useful platform I'll go hunt one down.

**Comment by timbobcat** [comment]
Awesome! You could use this: https://www.mouser.dk/ProductDetail/Nordic-Semiconductor/nRF52840-DK?qs=F5EMLAvA7IA76ZLjlwrwMw%3D%3D

**Comment by RobMeades** [comment]
Yup, have ordered one and, I had forgotten, our NINA-B3 module also has an NRF52840 inside so am tracking down a board with one of those on also.

**Comment by RobMeades** [comment]
Hi again: it may have taken more than a year so you are probably not interested and rather a lot has happened in the world in that time but I just thought I'd mention that the successor to this repo now, finally, has TLS security fully implemented:

https://github.com/u-blox/ubxlib
